name: Test CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Testcontainers Cloud Client
        uses: atomicjar/testcontainers-cloud-setup-action@v1
        with:
            token: ${{ secrets.TC_CLOUD_TOKEN }}

      - name: Install bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ secrets.BUN_VERSION }}


      - name: Install deps
        run: bun i

      - name: Lint
        run: bun run lint

      - name: Test and coverage
        run: bun run test:coverage
        env:
          DATABASE_TEST_URL: ${{ secrets.DATABASE_TEST_URL }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # required
